esphome:
  name: doorbell
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "Giga"
  password: "1234"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Giga4"
    password: "1234"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "doorbell"

ota:
  password: "doorbell"

# Doorbell Button GPIO 0
door_bell_button_option:
  # Basic:
  pin: D0

  # Advanced:
  pin:
    number: D0
    inverted: True
    mode: INPUT_PULLUP


